cmake: fix unit tests compilation with systemd
By enabling the WITH_SYSTEMD and WITH_DLT_UNIT_TESTS cmake flags
the build will fail with an error due to a linking issue:

../src/daemon/libdlt_daemon.so: undefined reference to `sd_booted'
collect2: error: ld returned 1 exit status

Signed-off-by: Gordan Markuš <gordan.markus@pelagicore.com>