Fix compile failure related to gzlog
* In commit [1], gzlog is changed from gzFile to gzFile*, this cause
  failure:
/dlt-daemon/src/offlinelogstorage/dlt_offline_logstorage.c:88:21: error: passing argument 1 of ‘gzclose’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   88 |         gzclose(data->gzlog);
      |                 ~~~~^~~~~~~
      |                     |
      |                     struct gzFile_s **
compilation terminated due to -Wfatal-errors.

so change gzlog back to gzFile, so that all the gzxxx function can work
well.

* Change to gzFile causes the following failure, since fileno need
  FILE*, according to code "config->gzlog = gzdopen(config->fd, mode)",
  seems we don't need to use fileno, just use config->fd is ok.
/dlt-daemon/src/offlinelogstorage/dlt_offline_logstorage_behavior.c:1133:48: error: passing argument 1 of ‘fileno’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 1133 |                         if (fsync(fileno(config->gzlog)) != 0) {
      |                                          ~~~~~~^~~~~~~
      |                                                |
      |                                                gzFile {aka struct gzFile_s *}
compilation terminated due to -Wfatal-errors.

[1] https://github.com/COVESA/dlt-daemon/commit/543087ba98c103dc576edadeccf614c9dab1b9b3

Signed-off-by: Changqing Li <changqing.li@windriver.com>