fix warning of self assign
use (void)xyz instead of self assign
error log:
error: explicitly assigning value of variable of type 'void *' to
itself
      [-Werror,-Wself-assign]

Signed-off-by: Phong Tran <tranmanphong@gmail.com>