dlt-control-common: Fix build with GCC 8
When the "stringop-truncation" warning is treated as an error, the build
fails with the following message:

dlt-control-common.c:213:29: error: ‘strncpy’ output may be truncated
copying 255 bytes from a string of length 1023 [-Werror=stringop-truncation]

On this file we want to truncate the string due to the destination
buffer size, so fix the above by using memcpy() instead.

Signed-off-by: Jesus Sanchez-Palencia <jesus.sanchez-palencia@intel.com>